# Generated by Django 5.2.5 on 2025-08-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(help_text='Например: Московская', verbose_name='Область')),
                ('district', models.CharField(help_text='Например: Подольский', verbose_name='Район')),
                ('city', models.CharField(help_text='Например: Подольск', verbose_name='Город')),
                ('street', models.CharField(help_text='Например: ул. Профсоюзная или пр-т Юных Ленинцев', verbose_name='Улица')),
                ('house_number', models.CharField(help_text='Например: 10 или 10к1', verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_author', models.CharField(help_text='Имя автора', verbose_name='Автор')),
                ('name_coauthor', models.CharField(blank=True, help_text='Соавторы при наличии', null=True, verbose_name='Соавтор(-ы)')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_organization', models.CharField(help_text='Название организации', max_length=100, verbose_name='Название')),
                ('inn_organization', models.CharField(help_text='ИНН организации из 12 цифр', max_length=12, verbose_name='ИНН')),
                ('type_organization', models.CharField(choices=[('1', 'Школа'), ('2', 'Колледж'), ('3', 'Университет')], help_text='Вид организации', verbose_name='Вид')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Publishings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_publishing', models.CharField(help_text='Название издательства', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_structure', models.CharField(help_text='Название структурного подразделения', max_length=100, verbose_name='Название')),
                ('adress_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library_app.addresses', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel_class', models.CharField(default=0, verbose_name='Параллель')),
                ('name_class', models.CharField(help_text='Название класса', unique=True, verbose_name='Название')),
                ('name_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.structures', verbose_name='Название школы')),
            ],
            options={
                'verbose_name': 'класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.CharField(unique=True, verbose_name='id книги')),
                ('name_book', models.CharField(help_text='Название книги/учебника', verbose_name='Название')),
                ('category_book', models.CharField(choices=[('schoolbook', 'Учебник'), ('literature', 'Художественная литература')], default='Учебник', verbose_name='Категория')),
                ('publishing_yearv', models.IntegerField(verbose_name='Год изданя')),
                ('author_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.authors', verbose_name='Автор')),
                ('publishing_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.publishings', verbose_name='Издательство')),
                ('name_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.structures', verbose_name='Название школы')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='UsersLibrary',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False, verbose_name='id пользователя')),
                ('last_name_user', models.CharField(verbose_name='Фамилия')),
                ('first_name_user', models.CharField(verbose_name='Имя')),
                ('patronymic_user', models.CharField(blank=True, help_text='При наличии', null=True, verbose_name='Отчество')),
                ('phone_user', models.CharField(help_text='Пример: +7-999-999-99-99', verbose_name='Телефон')),
                ('mail_user', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('status_user', models.CharField(choices=[('student', 'ученик'), ('teacher', 'учитель')], verbose_name='Статус')),
                ('classroom_teacher', models.BooleanField(blank=True, default=False, null=True, verbose_name='Классное руководство')),
                ('name_class', models.ForeignKey(blank=True, help_text='При наличии', null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.classes')),
                ('name_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.structures', verbose_name='Название школы')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
